## ENVIRONMENT ----------------------------------------------------

## All key-value pairs in the [env] section will be added as environment variables for any process spawned
## by Alacritty, including its shell. Some entries may override variables set by alacritty itself.
[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

## WINDOW ---------------------------------------------------------
[window]
position = "None"
dynamic_padding = true
decorations = "full"
opacity = 0.9
blur = false
startup_mode = "Windowed"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"

## Number of lines/columns (not pixels) in the terminal.
[window.dimensions]
columns = 82
lines = 24

## Blank space added around the window in pixels.
[window.padding]
x = 0
y = 0

## SCROLLING ------------------------------------------------------
[scrolling]
history = 10000
multiplier = 3

## SELECTION ------------------------------------------------------
[selection]
save_to_clipboard = true

## CURSOR ---------------------------------------------------------
[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "On"

## MOUSE ----------------------------------------------------------
[mouse]
hide_when_typing = false

## HINTS ----------------------------------------------------------
[[hints.enabled]]
command         = "xdg-open"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "U", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

## DEBUG ----------------------------------------------------------
[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false

[general]
## Import additional configuration files.
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]
## Live config reload
live_config_reload = true


## Offer IPC using alacritty msg
ipc_socket = true


