[font]
# Font size in points
size = 10
builtin_box_drawing = true

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "ExtraBold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
