#!/bin/env bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

# Define the paths for Zsh and Nushell
zsh_path="/usr/bin/zsh"
nu_path="/usr/bin/nu"

# Function to change the shell with colored output
change_shell() {
    chsh -s "$1"
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}Shell successfully changed to $1.${RESET}"
        echo -e "${YELLOW}Please log out and log back in to apply the changes.${RESET}"
    else
        echo -e "${RED}Failed to change shell.${RESET}"
    fi
}

# Function to display usage instructions
show_usage() {
    echo -e "${BLUE}Usage: cshell [nu|zsh]${RESET}"
}

# Check the argument and change the shell accordingly
if [[ "$1" == "nu" ]]; then
    echo -e "${BLUE}Switching to Nushell...${RESET}"
    change_shell "$nu_path"
elif [[ "$1" == "zsh" ]]; then
    echo -e "${BLUE}Switching to Zsh...${RESET}"
    change_shell "$zsh_path"
else
    echo -e "${RED}Invalid argument!${RESET}"
    show_usage
    exit 1
fi
