#! /bin/sh
## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"
SXHKDIR="$HOME/.config/sxhkd"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'


## Bspwm colors
BSPWM_FBC='#83a598'  # Gruvbox bright blue
BSPWM_NBC='#3c3836'  # Gruvbox dark black
BSPWM_ABC='#d3869b'  # Gruvbox bright purple
BSPWM_PFC='#b8bb26'  # Gruvbox bright yellowish green

## Bspwm appearance
BSPWM_BORDER='2'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
default_workspaces() {
	for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
	  bspc monitor "$monitor" -d '' '' '' '' '' '' '' ''
	done
}

# default
default_workspaces

## Apply bspwm configurations

bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

## remove all rules first
bspc rule -r *:*

# kitty always in 1
bspc rule -a kitty desktop='^1' follow=on focus=on

# web
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on focus=on

## 3 > files (always open file manager on workspace-3)
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in "${files[@]}"; do
   bspc rule -a "$i" desktop='^3' follow=on focus=on; done

## 4 > code (always open editors on workspace-4)
declare -a code=(Geany code-oss Code vim)
for i in ${code[@]}; do
   bspc rule -a "$i" desktop='^4' follow=on focus=on; done


## 5 > office and docs (always open office/doc apps on workspace-5)
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice \
obsidian
)
for i in ${office[@]}; do
   bspc rule -a "$i" desktop='^5' follow=on focus=on; done

## 6 > communication (always open communication apps on workspace-6)
declare -a comm=(TelegramDesktop vesktop)
for i in ${comm[@]}; do
   bspc rule -a "$i" desktop='^6' follow=on focus=on; done

## 7 > media (always open media apps on workspace-7)
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs Spotify)
for i in ${media[@]}; do
   bspc rule -a "$i" desktop='^7'  follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## autostart ------------------------------------#

# Lauch keybindings daemon
sxhkd -c "$SXHKDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr


bspbar
bspcomp
bspdunst &
nitrogen --restore &

# picom --config /home/.config/picom/picom.conf &
# polybar &
