#!/usr/bin/env bash

# Icons
iDIR='/usr/share/icons/Adwaita/symbolic/status'

# Graphics card
CARD=$(find /sys/class/backlight | head -n 1)

# Get brightness
get_backlight() {
    if [[ "$CARD" == *"intel_"* ]]; then
        BNESS=$(brillo -G)
        LIGHT=${BNESS%.*}
    else
        LIGHT=$(printf "%.0f\n" "$(brillo -G)")
    fi
    echo "${LIGHT}%"
}

# Get icons
get_icon() {
    backlight="$(get_backlight)"
    current="${backlight%%%}"
    if [[ "$current" -ge "0" && "$current" -le "20" ]]; then
        icon="$iDIR"/display-brightness-symbolic.svg
    elif [[ "$current" -ge "20" && "$current" -le "40" ]]; then
        icon="$iDIR"/display-brightness-symbolic.svg
    elif [[ "$current" -ge "40" && "$current" -le "60" ]]; then
        icon="$iDIR"/display-brightness-symbolic.svg
    elif [[ "$current" -ge "60" && "$current" -le "80" ]]; then
        icon="$iDIR"/display-brightness-symbolic.svg
    elif [[ "$current" -ge "80" && "$current" -le "100" ]]; then
        icon="$iDIR"/display-brightness-symbolic.svg
    fi
}

# Notify 
notify_bl() {
    get_icon && dunstify -u low -h string:x-dunst-stack-tag:obbacklight -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
    brillo -q -A 10 && notify_bl
}

# Decrease brightness
dec_backlight() {
    brillo -q -U 10 && notify_bl
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    get_backlight
elif [[ "$1" == "--inc" ]]; then
    inc_backlight
elif [[ "$1" == "--dec" ]]; then
    dec_backlight
else
    get_backlight
fi
